---
- name: To download files on remote
  hosts: all
  become: true

  tasks: 
  - name: Download a package from the internet
    get_url:
      url: https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tar.xz
      dest: /home/srikanth
      owner: srikanth
      group: srikanth
      mode: 0777
