---
- name: Using tags to run the playbook for a single task.
  hosts: all
  become: true

  tasks:
  - name: Install nginx eackage
    yum:
      name: nginx
      state: present
    tags: i-nginx

  - name: Start the nginx service
    service:
      name: nginx
      state: started
      enabled: true
    tags: ss-nginx
