---
- name: Using tags to run the playbook for a single task.
  hosts: all
  become: true
  vars:
  - apps: [nginx,httpd,vim,netcat]

  tasks:
  - name: Install multiple package
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ apps }}"
