---
- name: Installing a package and starting the service
  hosts: all
  become: true

  tasks:
  - name: Install nginx eackage
    yum:
      name: nginx
      state: present
  - name: Start the nginx service
    service:
      name: nginx
      state: started
      enabled: true
