---
# tasks file for httpd_setup
- name: To install httpd on remote server
  become: true
  yum: 
    name: "{{ httpd_package_name }}"
    state: present

- name: To copy the html file to destination
  become: true
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: start the httpd service
  become: true
  service:
    name: "{{ httpd_package_name }}"
    state: started
    enabled: yes
